name: single-location-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.9.19
  - jupyterlab=4.2.3
  - matplotlib=3.8.4
  - pandas=2.2.2
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - transformers=4.26.1